# Generated by Django 3.0.8 on 2020-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='expert',
            field=models.ManyToManyField(null=True, through='candidate.specialty', to='candidate.expertise'),
        ),
    ]
