# Generated by Django 3.0.8 on 2020-08-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_candidates_votes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together=set(),
        ),
    ]
